session_name: bitbunny
start_directory: $HOME/Projects/bitbunny-app
windows:
  - window_name: nvim
    panes:
      - nvim
  - window_name: shell 
    layout: main-vertical
    panes:
      - "echo shell"
