[tasks.default]
description = "Run all tasks (default)"
depends = [
  "mise",
  "nvim",
  "zellij"
]

[tasks.mise]
description = "Configure mise"
run = '''
#!/usr/bin/env bash
./ensure.py link $HOME/.config/mise ./mise
'''

depends = [
  "config-dir"
]

[tasks.nvim]
description = "Configure neovim"

run = '''
#!/usr/bin/env bash
./ensure.py link $HOME/.config/nvim ./nvim
nvim --headless "+Lazy! sync" +qa
'''

depends = [
  "config-dir"
]

[tasks.zellij]
description = "Configure zellij"
run = '''
#!/usr/bin/env bash
./ensure.py link $HOME/.config/zellij ./config/zellij
'''

[tasks.nushell]
description = "Configure nushell"
run = '''
#!/usr/bin/env bash
./ensure.py link $HOME/.config/nushell ./nushell
cargo install nu_plugin_skim
'''

[tasks.config-dir]
description = "Ensure the config directory exists"
run = '''
#!/usr/bin/env bash
./ensure.py dir $HOME/.config
'''


[settings]
experimental = true

[tools]
python = "3.10.11"
