[tasks.default]
description = "Run all tasks (default)"
depends = [
  "mise",
  "nvim",
  "zellij",
  "nushell",
  "atuin",
  "tmuxp",
]

[tasks.tmuxp]
description = "Configure tmuxp"
run = '''
#!/usr/bin/env bash
  './ensure.py link $HOME/.config/tmuxp ./config/tmuxp'
'''
depends = [
  "config-dir"
]

[tasks.mise]
description = "Configure mise"
run = '''
#!/usr/bin/env bash
./ensure.py link $HOME/.config/mise ./mise
'''

depends = [
  "config-dir"
]

[tasks.nvim]
description = "Configure neovim"

run = '''
#!/usr/bin/env bash
./ensure.py link $HOME/.config/nvim ./nvim
nvim --headless "+Lazy! sync" +qa
'''

depends = [
  "config-dir"
]

[tasks.zellij]
description = "Configure zellij"
run = '''
#!/usr/bin/env bash
./ensure.py link $HOME/.config/zellij ./config/zellij
'''

[tasks.nushell]
description = "Configure nushell"
run = '''
#!/usr/bin/env bash
./ensure.py link $HOME/.config/nushell ./nushell
cargo install nu_plugin_skim nu_plugin_polars nu_plugin_formats nu_plugin_gstat nu_plugin_query nu_plugin_inc --locked
'''

[tasks.atuin]
description = "Configure atuin"
run = '''
#!/usr/bin/env bash
./ensure.py link $HOME/.config/atuin ./config/atuin
./ensure.py link $HOME/Library/LaunchAgents/com.atuin.daemon.plist ./config/atuin/com.atuin.daemon.plist
launchctl load $HOME/Library/LaunchAgents/com.atuin.daemon.plist
launchctl start com.atuin.daemon
'''

[tasks.config-dir]
description = "Ensure the config directory exists"
run = '''
#!/usr/bin/env bash
./ensure.py dir $HOME/.config
'''


[settings]
experimental = true

[tools]
python = "3.10.11"
