[tasks.default]
description = "Run all tasks"

depends = [
  "mise",
  "nvim",
]

[tasks.tmuxp]
description = "Configure tmuxp"
run = [
  './ensure.py link $HOME/.config/tmuxp ./config/tmuxp'
]
depends = [
  "config-dir"
]

[tasks.mise]
description = "Configure mise"
run = [
  './ensure.py link $HOME/.config/mise ./mise'
]
depends = [
  "config-dir"
]

[tasks.nvim]
description = "Configure neovim"

run = [
  './ensure.py link $HOME/.config/nvim ./nvim',
  'nvim --headless "+Lazy! sync" +qa'
]

depends = [
  "config-dir"
]

[tasks.config-dir]
description = "Ensure the config directory exists"
run = [
  './ensure.py dir $HOME/.config'
]


[settings]
experimental = true

[tools]
python = "3.10.11"
