[tools]
node = "22"
pnpm = "9"
python = "3.12"
"npm:node-gyp" = "latest"
"npm:insect" = "latest"
"npm:@githubnext/github-copilot-cli" = "latest"
"npm:@usebruno/cli" = "latest"
"pipx:aider-chat" = "latest"

[settings]
experimental = true
