[tools]
node = "22"
pnpm = "9"
python = "3.12"
"npm:node-gyp" = "latest"
"npm:insect" = "latest"
"npm:@githubnext/github-copilot-cli" = "latest"
"npm:@usebruno/cli" = "latest"
"npm:devspace" = "latest"
"npm:@google/clasp" = "latest"
"npm:@fsouza/prettierd" = "latest"
elixir = "latest"
erlang = "latest"
pulumi = "latest"
azure-cli = "latest"
rye = "latest"
java = "latest"
bun = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
delta = "latest"
"npm:eas-cli" = "latest"
"pipx:aider-chat" = "latest" 
"npm:playwright" = "latest"

[settings]
experimental = true
