[tools]
node = "22"
pnpm = "9"
python = "3.12"
"npm:node-gyp" = "latest"
"npm:insect" = "latest"
"npm:@githubnext/github-copilot-cli" = "latest"
"npm:@usebruno/cli" = "latest"
"pipx:aider-chat" = "v0.36"
"npm:devspace" = "latest"
"npm:@google/clasp" = "latest"
neovim = "latest"
elixir = "latest"
erlang = "latest"

[settings]
experimental = true
