[tools]
node = "22"
pnpm = "9"
python = "3.12"
"npm:node-gyp" = "latest"
"npm:insect" = "latest"
"npm:@githubnext/github-copilot-cli" = "latest"
"npm:@usebruno/cli" = "latest"
"npm:devspace" = "latest"
"npm:@google/clasp" = "latest"
"npm:@fsouza/prettierd" = "latest"
neovim = "latest"
elixir = "latest"
erlang = "latest"
pulumi = "latest"
azure-cli = "latest"
rye = "latest"
java = "latest"

[settings]
experimental = true
