#!/usr/bin/env sh

yabai -m config \
  layout bsp \
  external_bar all:0:26 \
  window_placement second_child

yabai -m rule --add app="^시스템 설정$" manage=off
yabai -m rule --add app="^시스템 정보$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Dash$" manage=off
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add app="^Steam$" manage=off

yabai -m space 1 --label main

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add app='^Ghostty$' event=window_created action='yabai -m space --layout bsp'
yabai -m signal --add app='^Ghostty$' event=window_destroyed action='yabai -m space --layout bsp'

echo "yabai configuration loaded.."
