#!/usr/bin/env sh

yabai -m config \
  layout bsp \
  external_bar all:0:29 \
  window_placement second_child

yabai -m rule --add app="^시스템 설정$" manage=off
yabai -m rule --add app="^시스템 정보$" manage=off
yabai -m rule --add app="^Dash$" manage=off
yabai -m rule --add app="^1Password$" manage=off

yabai -m space 1 --label main

yabai -m signal --add event=window_focused action="hs -c \"yabaidirectcall.window_focused(\`printenv YABAI_WINDOW_ID\`)\""
yabai -m signal --add event=application_activated action="hs -c \"yabaidirectcall.application_activated(\`printenv YABAI_PROCESS_ID\`)\""
yabai -m signal --add event=window_resized action="hs -c \"yabaidirectcall.window_resized(\`printenv YABAI_WINDOW_ID\`)\""
yabai -m signal --add event=window_moved action="hs -c \"yabaidirectcall.window_moved(\`printenv YABAI_WINDOW_ID\`)\""
yabai -m signal --add event=window_destroyed action="hs -c \"yabaidirectcall.window_destroyed(\`printenv YABAI_WINDOW_ID\`)\""

echo "yabai configuration loaded.."
